### ISSUE TITLE
Can't drag-and-drop to-do items from one group to another

### ISSUE THREAD

**Issue by BenjaminRaison** [tonyfederer/OutlookFileDrag#11]
When in Outlook's to-do view, with items grouped by due date, trying to drag an item from one group to another causes the following error:

```Cannot move the items. The folders you are trying to change do not support the operation. Could not complete the operation because the service provider does not support it.```

Details:
* Windows 7 x64
* Outlook 2010
* OutlookFileDrag 1.0.1

Probably the same cause as #1

**Comment by tonyfederer** [comment]
This may be fixed in version 1.0.3.  Please test and let me know if you still experience this issue.

**Comment by tonyfederer** [comment]
Closing issue due to no response.

**Comment by BenjaminRaison** [comment]
Sorry it took me so long to answer. Can confirm the fix, thank you very much!😀
