### ISSUE TITLE
OutlookFileDrag: Publisher can not be verified.

### ISSUE THREAD

**Issue by balavigneshkumar9** [tonyfederer/OutlookFileDrag#12]
Hi Team,

We have installed "OutlookFileDrag" in Windows 10 machine where Outlook is installed. After installation when we open Outlook, we have received the pop-up message "Publisher can not be verified" with two options "Install" and "Don't Install". After Click on 'Don't Install', we have verified the the outlook add-ins list 'OutllookFileDrag' is showing as in Inactive Application Add-ins.
 I have attached the screen shot for your reference. We would like to suppress the extra Pop-up after installation.  Could you please provide your suggestion to fix the issue.

Thanks and Regards,
Vignesh Kumar Balakrishnan
![outlook_popup](https://user-images.githubusercontent.com/44194985/47008441-a2891000-d13a-11e8-8c29-9c2695da65dd.PNG)

**Comment by TonyWilsonMosman** [comment]
My apologies if I misunderstood you, but if you say that you clicked "Don't Install" in Outlook, then you are telling Outlook not to trust the plug in and that is the reason why it appears as inactive. 

I am guessing you need to click "install" to activate the plug in and have that pop-up stop, or uninstall the plug in from windows all together.

Add-ins and Macros need to be trusted in Outlook to work. The security settings > Trust Center in Outlook has the options to trust non-Microsoft add-ins. 

Hope this helps!

**Comment by tonyfederer** [comment]
Correct, you will need to click Install to install the add-in.  This warning appears because I have not purchased a code signing certificate.  If you trust me, then you can safely click Install.

**Comment by balavigneshkumar9** [comment]
Hi,

Thanks for your comments. 

Could you please let me know if you have any idea to suppress this pop-up while opening Outlook?

Thanks and Regards,
Vignesh Kumar Balakrishnan

**Comment by tonyfederer** [comment]
Since this is open-source software, I will not be purchasing a code signing certificate, which would be required in order to suppress "Unknown Publisher" warnings.  If users trust this add-in, they can click Install and they will not see the message again.

**Comment by DJM4693** [comment]
I clicked on Don't Install and now can not re-install to give OutloookfileDrag rights to work.
