### ISSUE TITLE
Issue with Outlook 365 (2016) and MS Dynamics AX 2009

### ISSUE THREAD

**Issue by JRVocke** [tonyfederer/OutlookFileDrag#18]
Hi we are using OutlookFileDrag with Outlook 2016 and it is working fine with Sharepoint Online (in Google Chrome). Except one thing; the option to drag e-mails from Outlook 2016 to MS Dynamics AX 2009 is broken. Is this a known issue? 
Can you please fix it?.
If we disable the Add-In "OutlookFileDrag" the drag option from Outlook 2016 to MS Dynamics AX 2009's Document Handling option is working fine. When OutlookFileDrag is enabled in Outlook, the emails dragged to MS Dynamics AX 2009 are recorded, but not handled properly.

**Comment by tonyfederer** [comment]
I do not have Dynamics AX, so I have not tested OutlookFileDrag with it, but I am not aware of any reason why it wouldn't work.  However, I would be happy to try to troubleshoot this issue with you.

To start, can you please delete the error log in the %appdata%\OutlookFileDrag folder, reproduce the issue, and then attach the log file so I can look through it?

**Comment by JRVocke** [comment]
Thank you Tony, a little background then.
We use Remote Desktop 2016 servers and Outlook 365/2016 with MS Dynamics AX 2009. In our case we can define in MS Dynamics AX 2009 (AX 2009), in the setup of the module Document Management/Document Handling where you want to receive the ‘dragged’ e-mails.
We use the network directory ‘K:\Dynarent\Documenten_PROD\Email2016\’. Then we drag the e-mail from Outlook (Inbox or Outbox) to AX 2009). It is then saved under the name ‘DHxxxxx_X.msg’ in this location (the network directory).
But with OutlookFileDrag ‘ON’ it looks like the ‘Drag’ action is completed, but the MSG file is not written to the K:\Dynarent\Documenten_PROD\Email2016\ location, but to : c:\Users\j.vocke\AppData\Local\Temp\7\OutlookFileDrag\. To be exactly to: c:\Users\j.vocke\AppData\Local\Temp\7\OutlookFileDrag\c4910615-de7c-47b3-b860-7637b96196f0\ .
And the name of the MSG file is; ‘Fox-IT_ Nederlandse bedrijven ook slachtoffer van SamSam-gijzelsoftware.msg’. The routine of Outlook/OutlookFileDrag performs the action and not the action of Outlook/AX 2009.
This causes a problem as the next time a user logs-in in the RDS Farm the location and the MSG file is not there anymore.
Is it possible that in this case (Outlook/MS Dynamics AX 2009) the OutlookFileDrag Add-In does not perform the action, but leaves it to Outlook/MS Dynamics AX 2009?

[cid:image001.png@01D48A61.04CF6AF0]

[cid:image003.png@01D48A62.4CC209C0]


[cid:image002.png@01D48A63.7BA5B600]

But the next time, a user gets the error:
[cid:image004.png@01D48A65.43F310C0]


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: zondag 2 december 2018 15:54
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; Author <author@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)


I do not have Dynamics AX, so I have not tested OutlookFileDrag with it, but I am not aware of any reason why it wouldn't work. However, I would be happy to try to troubleshoot this issue with you.

To start, can you please delete the error log in the %appdata%\OutlookFileDrag folder, reproduce the issue, and then attach the log file so I can look through it?

**Comment by JRVocke** [comment]
With OutlookFileDrag this happens when you drag an email from Outlook to AX2009. You have to press 'Toestaan/Allow' 4 times or tick the ‘Toegang geven voor / Give access’ box...
And the email will be in the right place in AX 2009 and in the directory.

[cid:image001.png@01D48A66.61806A10]

[cid:image002.png@01D48A66.61806A10]





Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: zondag 2 december 2018 15:54
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; Author <author@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)


I do not have Dynamics AX, so I have not tested OutlookFileDrag with it, but I am not aware of any reason why it wouldn't work. However, I would be happy to try to troubleshoot this issue with you.

To start, can you please delete the error log in the %appdata%\OutlookFileDrag folder, reproduce the issue, and then attach the log file so I can look through it?

**Comment by tonyfederer** [comment]
The pictures are not showing on your post.  Can you please attach them?

**Comment by JRVocke** [comment]
Hi Tony, please find the MSG and picture files included in this ZIP archive.


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: donderdag 6 december 2018 06:21
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; Author <author@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)


The pictures are not showing on your post. Can you please attach them?

**Comment by tonyfederer** [comment]
Sorry, I still don't see any attachments.  Can you please use this link to access the issue and upload the files manually?

https://github.com/tonyfederer/OutlookFileDrag/issues/18

**Comment by JRVocke** [comment]
Please find the pictures from the above comments.

![second_picture_2](https://user-images.githubusercontent.com/45534692/49684592-1eb62900-fad6-11e8-8505-92a853f3df9b.png)
![first_picture_2](https://user-images.githubusercontent.com/45534692/49684593-1eb62900-fad6-11e8-8515-f15c14f21df5.png)
![fourth_picture_1](https://user-images.githubusercontent.com/45534692/49684594-1f4ebf80-fad6-11e8-89d2-76c0b1efdd46.png)
![third_picture_1](https://user-images.githubusercontent.com/45534692/49684595-1f4ebf80-fad6-11e8-9bcb-5ad0339dfd8d.png)
![second_picture_1](https://user-images.githubusercontent.com/45534692/49684596-1f4ebf80-fad6-11e8-8649-e35cecbe8bed.png)
![first_picture_1](https://user-images.githubusercontent.com/45534692/49684597-1f4ebf80-fad6-11e8-8834-6be41876268c.png)

**Comment by JRVocke** [comment]
I did my best to add the Pictures. I edited the comments and added the images in a new comment (4 pieces and 2 pieces), The log file was received?


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: zaterdag 8 december 2018 03:12
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; Author <author@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)


Sorry, I still don't see any attachments. Can you please use this link to access the issue and upload the files manually?

#18<https://github.com/tonyfederer/OutlookFileDrag/issues/18>

**Comment by tonyfederer** [comment]
This security warning should not occur if you are running Outlook's default security settings.  The default Outlook security setting for programmatic access is "Warn me about suspicious activity when my antivirus software is inactive or out of date".

Please check that your antivirus is reporting as valid using these steps:

1. In Outlook, go to File > Options.
2. Click Trust Center.
3. Click Trust Center settings.
4. Click Programmatic access.
5. Make sure that your antivirus status is "Valid".

![outlook programmatic access](https://user-images.githubusercontent.com/37388218/49778088-022e1280-fcc9-11e8-8ae9-cf3cde41c357.PNG)

**Comment by JRVocke** [comment]
In trustcenter / programmatic access it says:
Antivirus status is not available. This version of Windows does not support antivirus detection. (Antivirusstatus is niet beschikbaar. Deze versie van Windows ondersteund geen antivirusdetectie). We run on Windows 2016 RDS LTSB. build 14393.2641


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: dinsdag 11 december 2018 05:16
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)


This security warning should not occur if you are running Outlook's default security settings. The default Outlook security setting for programmatic access is "Warn me about suspicious activity when my antivirus software is inactive or out of date".

Please check that your antivirus is reporting as valid using these steps:

  1.  In Outlook, go to File > Options.
  2.  Click Trust Center.
  3.  Click Trust Center settings.
  4.  Click Programmatic access.
  5.  Make sure that your antivirus status is "Valid".

[Afbeelding verwijderd door afzender. outlook programmatic access]<https://user-images.githubusercontent.com/37388218/49778088-022e1280-fcc9-11e8-8ae9-cf3cde41c357.PNG>

**Comment by JRVocke** [comment]
Tony,

thank you for your reaction,
Can build in your exclusion list for programs. So for example if you run a Drag and Drop from Outlook to MS Dynamics AX 2009 ( ax32.exe ) you will not run OutlookFileDrag.


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: dinsdag 11 december 2018 05:16
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)


This security warning should not occur if you are running Outlook's default security settings. The default Outlook security setting for programmatic access is "Warn me about suspicious activity when my antivirus software is inactive or out of date".

Please check that your antivirus is reporting as valid using these steps:

  1.  In Outlook, go to File > Options.
  2.  Click Trust Center.
  3.  Click Trust Center settings.
  4.  Click Programmatic access.
  5.  Make sure that your antivirus status is "Valid".

[Afbeelding verwijderd door afzender. outlook programmatic access]<https://user-images.githubusercontent.com/37388218/49778088-022e1280-fcc9-11e8-8ae9-cf3cde41c357.PNG>

**Comment by tonyfederer** [comment]
There is no need to build an exclusion list because OutlookFileDrag can successfully drag and drop to any app that accepts file drop, including Dynamics AX 2009.  The security prompt would occur with any Outlook add-in, not just OutlookFileDrag.  According to this article, Outlook cannot detect antivirus state when installed on Windows Server:

https://support.microsoft.com/en-us/help/3190315/outlook-trust-center-shows-your-antivirus-status-as-unavailable-this-v 

Because of this, Outlook's default security setting for programmatic access of "Warn me about suspicious activity when my antivirus software is inactive or out of date" does not work properly.

In this scenario, to avoid the prompt, you would need to change your Outlook programmatic setting to "Never warn me about suspicious activity".

**Comment by JRVocke** [comment]
Hi, the error message where you are reffering to has nothing to do with antivirus, but the error occurs one day later because Windows 2016 Remote Desktop changes the TEMP directory location. The message file is not there anymore. Also your routine puts the file in TEMP and not in the location defined in AX 2009.


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: donderdag 13 december 2018 05:06
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)


There is no need to build an exclusion list because OutlookFileDrag can successfully drag and drop to any app that accepts file drop, including Dynamics AX 2009. The security prompt would occur with any Outlook add-in, not just OutlookFileDrag. According to this article, Outlook cannot detect antivirus state when installed on Windows Server:

https://support.microsoft.com/en-us/help/3190315/outlook-trust-center-shows-your-antivirus-status-as-unavailable-this-v

Because of this, Outlook's default security setting for programmatic access of "Warn me about suspicious activity when my antivirus software is inactive or out of date" does not work properly.

In this scenario, to avoid the prompt, you would need to change your Outlook programmatic setting to "Never warn me about suspicious activity".

**Comment by tonyfederer** [comment]
Sorry, my antivirus comment was regarding the popup where you have to click "Allow" ("Toestaan").  Regarding the file being saved to the temp folder, yes, this is how OutlookFileDrag works.

1. Outlook calls DoDragDrop Win32 API.
2. OutlookFileDrag intercepts DoDragDrop API call
3. OutlookFileDrag saved item being drapped to temp folder.
4. OutlookFileDrag starts new drag of original item, adding the file drop format (CF_HDROP) with the path to the file in the temp folder.
5. A background thread later deletes the file from the temp folder (by default after 60 minutes)

You were correct when you said "Is it possible that in this case (Outlook/MS Dynamics AX 2009) the OutlookFileDrag Add-In does not perform the action, but leaves it to Outlook/MS Dynamics AX 2009?"  This is exactly how OutlookFileDrag works.  It expects the receiving application to create a copy of the file (or for web applications, upload the file).  Based on your comments, it sounds like that Dynamics AX does not copy the file, but references the path to the original file (in the temp folder).

Is that correct?

**Comment by JRVocke** [comment]
Hello Tony, thanks for your reply.
from Outlook one can drag a email to AX 2009 Document Handling and deliver it to the Target-Rose (see screen shot in a previous message). If the mouse pointer hits the Target rose, you get the question (from Outlook?) about allowing the action.
If you allow this, AX 2009 will take over from that moment on and place the email MSG file in a directory already defined in AX 2009 and this is not the TEMP directory.
Also the MSG file is saved with a name defined (template) in AX 2009 (number sequences). Up to point 1 - call DoDragDrop - it seems to go the same way, but after that, in the case of the combination Outlook - AX 2009, it is different than what OutlookFileDrag does.





Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​

**Comment by tonyfederer** [comment]
If you take a file from your desktop and drag it onto the target rose, what
is the result?  Does the file get copied to the destination folder?

**Comment by JRVocke** [comment]
No, the file will remain on the original location (in this case the Desktop). In AX 2009 only a link to the location will be included.


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
Van: Tony Federer <notifications@github.com>
Verzonden: zaterdag 15 december 2018 16:32
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Joost Vocke <j.vocke@coolworld-rentals.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Issue with Outlook 365 (2016) and MS Dynamics AX 2009 (#18)

If you take a file from your desktop and drag it onto the target rose, what
is the result? Does the file get copied to the destination folder?

**Comment by tonyfederer** [comment]
Ok, that's what I thought.  Since the same issue occurs when dragging a file from the desktop, it shows the issue is on the Dynamics AX side, not OutlookFileDrag.  I think you need to look at modifying the X++ code that runs when a file is dropped on the target rose.  The link below shows an example of code that copies the dragged file to the configured archive folder and renames it to the next number in the sequence.

https://dynamicsaxgyan.wordpress.com/2011/04/10/easy-drag-and-drop-files-document-management-with-minimum-x-coding-dynamics-ax/

Hope this helps!

**Comment by JRVocke** [comment]
Hello Tony,

Do you see a possibility to make an exclusion for AX 2009 ( ax32.exe )?
We cannot and may not change anything in the code of AX 2009.


Best regards, Met vriendelijke groet,
Joost Vocke
Applications and Systems Manager
Bekijk hier onze online Product Catalogus.
Coolworld International B.V.
​Veerweg 10A
5145 NS  Waalwijk
The Netherlands
T:  +31 (0)416-688088
M:  +31 623161645
E:j.vocke@coolworld-rentals.com
I:  www.coolworld-rentals.com

​KVK:  11042476
​BTW: NL808119898B01
Disclaimer
​
