### ISSUE TITLE
Where can I donate?

### ISSUE THREAD

**Issue by adjenks** [tonyfederer/OutlookFileDrag#2]
Do you have a Paypal? Patreon? Some sort of avenue for donating?
All other drag and drop solutions were too costly but this one works and is free.
Where can I donate for the work you put into it?

![Link to gif of Frye Money Meme](http://i3.kym-cdn.com/photos/images/newsfeed/000/264/241/9e9.gif)

**Comment by tonyfederer** [comment]
I'm glad you find this project useful.  I, too, found the commercial add-ins way too expensive for this basic functionality, especially if you want to deploy it across all the computers in an entire organization. 

I added a donate button on the main page/readme file.  Thanks!
