### ISSUE TITLE
When dragging Email into a software ( webapplication) the Email is moved to "deleted items"

### ISSUE THREAD

**Issue by tdpagencies** [tonyfederer/OutlookFileDrag#21]
Dear Tony,

We've seen a similar topic regarding mails that move to the deleted items. You suggested to change the script but we are not able to change this because the online application we are working with is in oracle and there is no script available.

We are working with outlook 365. Can you please have a look and advise?

Many thanks.

Kind regards,
Tatiana

**Comment by tdpagencies** [comment]
Hi Tony,

Thanks for your reply. When we drag a file from our desktop it won’t be deleted. Only if we drag is from outlook ( office 365)


Met vriendelijke groeten,
Kind regards,

[logo ACB Agencies]
Tatiana De Pooter | Accounts
T: +32 3 546 44 28 | F: +32 3 303 70 19
accounts@acbgroup.be<mailto:accounts@acbgroup.be> | www.acbgroup.be<http://www.acbgroup.be/>
[Image result for linkedin vector image]<https://www.linkedin.com/company/acb-agencies/>
Please note as of 1st January 2019 our postal code has been changed to B-2180 Ekeren. Correct office address is Ferdinand Verbieststraat 7 B-D,B-2180 Ekeren.



Our contract is based exclusively on “Standard trading conditions of Belgian Freight Forwarders<https://www.acbgroup.be/wp-content/uploads/2018/11/standard-trading-conditions.pdf?&lang=en>” edition 2005, nr 0090237.

Join us in giving back:
[4Ocean Logo Blue]<https://4ocean.com/>

**Comment by kozakhs** [comment]
Hello Tony, 

we are facing similar problem. When I want to drag the message straight from Outlook 2013 into my webapp, the message moves into deleted items. Could you please give me an advice how to make the message copy to the webapp without deleting it? Thank you very much!

Best regards
Jan

**Comment by Echtelion** [comment]
Hi Tony,
First, thanks for the job done, it's really helpful for my customers.
I have the same issue when drag&droping the mail (not an attached file, but the whole email object).
I can't look at the code right now, but will do in some week and see if I can help with that.
Regards,
Romain

**Comment by Spekksaver** [comment]
Hi Tony,
Thanks for nice job!
I get the same issue when draging the whole email object.
Any advise/fix would be greatly appreciated!
Best regards
Frode

**Comment by tonyfederer** [comment]
Some applications set the drop effect to "move", which cause the original item to be deleted.  As a workaround, OutlookFileDrag now detects if dropped files are being moved and overrides the effect to "copy" so the original item is not deleted.  This change has been released in version 1.0.9.

https://github.com/tonyfederer/OutlookFileDrag/releases/tag/v1.0.9

**Comment by Echtelion** [comment]
Thanks !!

**Comment by kozakhs** [comment]
Thank you very much!

**Comment by Spekksaver** [comment]
Thanks Tony, Works Great now!
