### ISSUE TITLE
Crash on office 365 - windows 7 only

### ISSUE THREAD

**Issue by RichBalls** [tonyfederer/OutlookFileDrag#22]
When dragging an attachment from outlook 2016 (office 365) outlook crashes.

This only seems to affect windows 7, tested same vertion on windows 10 and there's no issue :/

**Comment by tonyfederer** [comment]
Can you please attach the log file found at %appdata%\OutlookFileDrag?

**Comment by tonyfederer** [comment]
Please try downloading version 1.0.8 and confirm whether this resolves your issue.

- [Download for 64-bit Windows (Outlook 32-bit or 64-bit)](https://github.com/tonyfederer/OutlookFileDrag/files/2815210/OutlookFileDragSetup_x64.zip)
- [Download for 32-bit Windows](https://github.com/tonyfederer/OutlookFileDrag/files/2815211/OutlookFileDragSetup.zip)

**Comment by RichBalls** [comment]
hey sorry tony only just spotted your reply! my apologies.
yes just tested that version, issue is resolved, perfect.
Thanks so much, we find this plugin very helpful!
