### ISSUE TITLE
Outlook crashes when drag and drop of an email (System.AccessViolationException)

### ISSUE THREAD

**Issue by schminkel** [tonyfederer/OutlookFileDrag#23]
When doing a drag and drop of an email to anywhere e.g. to the desktop outlook crashes and needs to be restarted. The following error will be shown:

- Outlook 365
- Windows 7

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	OUTLOOK.EXE
  Problem Signature 02:	16.0.11126.20266
  Problem Signature 03:	5c3945c7
  Problem Signature 04:	OutlookFileDrag
  Problem Signature 05:	1.0.5.0
  Problem Signature 06:	5c11d47d
  Problem Signature 07:	f
  Problem Signature 08:	72
  Problem Signature 09:	**System.AccessViolationException**
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033

Additional information about the problem:
  LCID:	1033
  skulcid:	1033

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\WINDOWS\system32\en-US\erofflps.txt

**Comment by tonyfederer** [comment]
Can you please attach the log file found at %appdata%\OutlookFileDrag?

**Comment by vtthuan** [comment]
Found a solution. As this [document ](https://docs.microsoft.com/en-us/windows/desktop/api/objidl/ne-objidl-tagtymed) of Microsoft, for _TYMED_ISTREAM_ and _TYMED_ISTORAGE_, **punkForRelease** member is not **NULL**, so DataObjectHelper must like this 

finally
            {
                //Release all unmanaged objects
                if (medium.pUnkForRelease == null && medium.tymed != TYMED.TYMED_ISTREAM && medium.tymed != TYMED.TYMED_ISTORAGE )
                {

**Comment by tonyfederer** [comment]
According to [this Microsoft page](https://docs.microsoft.com/en-us/windows/desktop/api/ole2/nf-ole2-releasestgmedium), if pUnkForRelease is not null, the provider of the medium (Outlook in this case) is responsible for releasing the medium.

However, I believe this is related to an issue I accidentally introduced in version 1.0.4 for TYMED types TYMED_ISTREAM and TYMED_ISTORAGE.  Those mediums were already being released in the ReadIStorageIntoStream and ReadIStreamIntoStream methods, and then I added the ReleaseStgMedium call in the GetFilenamesAnsi, GetFilenamesUnicode, and ReadFileContents method.  This caused the code to try to release those mediums twice.  I added the ReleaseStgMedium method to ensure the medium was always being released properly (even in the case of exceptions), so I removed the release call in the ReadIStorageIntoStream and ReadIStreamIntoStream methods.

Please try downloading version 1.0.8 and confirm whether this resolves your issue.

- [Download for 64-bit Windows (Outlook 32-bit or 64-bit)](https://github.com/tonyfederer/OutlookFileDrag/files/2815210/OutlookFileDragSetup_x64.zip)
- [Download for 32-bit Windows](https://github.com/tonyfederer/OutlookFileDrag/files/2815211/OutlookFileDragSetup.zip)

**Comment by tonyfederer** [comment]
Issue should be resolved in version 1.0.8.  Closing issue due to no response.
