### ISSUE TITLE
MS o365 add-on deployment

### ISSUE THREAD

**Issue by mcmspark** [tonyfederer/OutlookFileDrag#24]
My Collaboration and Exchange support department wants this as an add-in:
[https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
or
[https://docs.microsoft.com/en-us/outlook/add-ins/](https://docs.microsoft.com/en-us/outlook/add-ins/)

From my understanding, this drag-drop functionality will require client side deployment.
Can you tell me if you agree?

**Comment by tonyfederer** [comment]
Correct, this add-in requires client-side deployment, as it uses COM interop and DLL hooking to intercept the drag and drop call and convert the contents being dragged.  These methods are specific to the Windows platform.  The web-style Office add-ins referenced above contain HTML, CSS, and JavaScript and are platform-independent.
