### ISSUE TITLE
Server 2016

### ISSUE THREAD

**Issue by LisaCounsell** [tonyfederer/OutlookFileDrag#28]
hello, we are looking to upgrade our citrix farm to server 2016 using office 365 and wanted to check to see if Outlook File Drag will work in the new environment?

**Comment by tonyfederer** [comment]
I have not specifically tested OutlookFileDrag with Citrix on Server 2016, but I am not aware of any compatibility issues.  I recommend setting up a test environment with a trial installation of Citrix and Windows Server 2016.  This would allow you to test your apps to ensure compatibility before changing your production environment.

**Comment by LisaCounsell** [comment]
Hi Tony

Thank you for your reply.

Cheers
Lisa

**Comment by tonyfederer** [comment]
Lisa, I wanted to reach out and let you know that Chrome 76 that was released yesterday now natively supports drag and drop from Outlook.  If you run this browser, then OutlookFileDrag is no longer be needed.  You may want to test if this works in your environment.

**Comment by LisaCounsell** [comment]
Hi Tony, thank you for the information. I’ll have a look into this.

Lisa
