### ISSUE TITLE
Does it work with O365?

### ISSUE THREAD

**Issue by msanchezt** [tonyfederer/OutlookFileDrag#32]
Is the software compatible with Office 365 also?
Architectures of O365 and Outlook 2016 are similar, so I'm wondering if for O365 will also work.

**Comment by tonyfederer** [comment]
Yes, it works with the Office 365 version of Microsoft Outlook.

**Comment by seansmith** [comment]
Tony – is it possible for you to e-mail me outside of Git?

Sean Smith
Deputy Director
New York Prosecutors Training Institute
107 Columbia Street
Albany, NY  12210
Phone: 518-432-1100, ext. 207
Sean.Smith@NYPTI.org<mailto:Sean.Smith@NYPTI.org>
www.NYPTI.org<http://www.NYPTI.org>
