### ISSUE TITLE
D&D to MFC application

### ISSUE THREAD

**Issue by Rodeck500** [tonyfederer/OutlookFileDrag#33]
This looks like a very useful application. I have tried to use it to drag&drop emails from Outlook 2016 to a rare application called CAXA EDM. It's a Chinese PDM desktop application built on MFC. It sets both applications in a never ending waiting state though and Outlook will not be released until I have closed the CAXA EDM process by force. Should it work theoretically or? 
I have quite good contact with the CAXA company so I think I can ask them to check some things if I just know what to ask them to check. Any help in this matter is highly appreciated.

**Comment by tonyfederer** [comment]
Does this CAXA EDM program allow drag and drop from the desktop to the application?

**Comment by Rodeck500** [comment]
Yes, it works fine to drag&drop files from the desktop to CAXA EDM.

**Comment by tonyfederer** [comment]
OutlookFileDrag should allow drag and drop to any program that supports standard Windows drag and drop functionality.

Are any errors shown in the log file located in the %appdata%\OutlookFileDrag folder?

**Comment by tonyfederer** [comment]
Closing issue due to no response.
