### ISSUE TITLE
"File name or directory name is not valid" when dropping email

### ISSUE THREAD

**Issue by EnricoUni** [tonyfederer/OutlookFileDrag#7]
Hello,
our platform is Outlook 2016 Home & Business 32bit: when dropping email (always: on filesystem, or on another Outlook folder, or on web browser) the "File name or directory name is not valid" error is raised.
Despite this error, drag & drop ends successfully.
We don't have exceptions on log file, or on windows event log.

No error or warning on Outlook 2016 Standard or 2016 Professional.

Thank you!

**Comment by EnricoUni** [comment]
Thank you TonyWilsonMosman for your help!
We've already read about KB3115158: the problem occurred on an older version of Outlook (2013), and we tryed all the same to find the KB on our machines, but we didn't find anything.
We also tried the suggestion about the registry (HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders), but this was useless too.

**Comment by tonyfederer** [comment]
Does this error still occur with the add-in disabled?

**Comment by EnricoUni** [comment]
No, when the add-in is stopped this error disappears.

**Comment by tonyfederer** [comment]
Can you please try installing OutlookFileDrag v1.0.2 and see if the issue still persists?

**Comment by EnricoUni** [comment]
> 
> 
> Can you please try installing OutlookFileDrag v1.0.2 and see if the issue still persists?

Hi tonyfederer, thank you for your answer!
I tried last and previous versions, and I tried to refer previous versions of EasyHook, too: the error continues to appear on Home & Business versions.

**Comment by tonyfederer** [comment]
What version of Windows 10 are you on?  According to [this post](https://answers.microsoft.com/en-us/office/forum/office_2016-outlook/drag-and-drop-in-outllok-2016-stopped-working/db41b545-6bf1-4f28-9ef0-24cb1e59c4dc), there was an issue with the Windows Anniversary Update that caused this issue in Outlook 2016.  A fix was released on December 13, 2016.

**Comment by tonyfederer** [comment]
Closing issue due to no response.
